### ISSUE TITLE
Not working with repeatable component on Strapi 4.12.6 

### ISSUE THREAD

**Issue by RiusmaX** [Freyb/strapi-plugin-copy-component#2]
Hi,

The plugin is not working on my Strapi (v4.12.6 - Docker).

Reproduce : 

1. Install the plugin and follow the config documentation (I use an uid : api::property.property)
2. Copy a repeatable component from another published entity with the button
3. Select the target container ("features" in my case)
4. Select source UID ("Property" in my case) and click "Next"
5. Page crash with this error :

`main.179de1d9.js:1992 TypeError: T is not a function
    at Js (main.179de1d9.js:1992:23091)
    at Co (main.179de1d9.js:1992:24880)
    at yt (main.179de1d9.js:1992:43470)
    at q0 (main.179de1d9.js:1992:42515)
    at c0 (main.179de1d9.js:1992:41538)
    at ed (main.179de1d9.js:1992:38031)
    at vl (main.179de1d9.js:1990:3291)
    at main.179de1d9.js:1992:35375
overrideMethod @ console.js:213
Ba @ main.179de1d9.js:1992
we.componentDidCatch.T.callback @ main.179de1d9.js:1992
O1 @ main.179de1d9.js:1990
lu @ main.179de1d9.js:1992
Fa @ main.179de1d9.js:1992
Fa @ main.179de1d9.js:1992
Fa @ main.179de1d9.js:1992
ol @ main.179de1d9.js:1992
q0 @ main.179de1d9.js:1992
c0 @ main.179de1d9.js:1992
ed @ main.179de1d9.js:1992
vl @ main.179de1d9.js:1990
(anonymous) @ main.179de1d9.js:1992
Show 1 more frame
Show less
2main.179de1d9.js:1992 TypeError: T is not a function
    at Js (main.179de1d9.js:1992:23091)
    at Co (main.179de1d9.js:1992:24880)
    at yt (main.179de1d9.js:1992:42986)
    at q0 (main.179de1d9.js:1992:42515)
    at c0 (main.179de1d9.js:1992:41538)
    at ed (main.179de1d9.js:1992:38031)
    at vl (main.179de1d9.js:1990:3291)
    at main.179de1d9.js:1992:35375` 

Plugin seems to be broken,
What can i do ?

Thanks in advance for your help,

Best regards,
